# Site settings
title: YogaRuka — Yoga Studio
email: studio@yogaruka.com
description: "YogaRuka is helping people in Sydney get on top of their physical and mental health, and build healthy habits. Our classes are available both in studio and online!"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yogaruka.com" # the base hostname & protocol for your site
permalink: /:categories/:title

# Build settings
markdown: kramdown
